import NavBar from '../components/navBar'; 
import Head from 'next/head';
import Link from 'next/link';
import FooterBar from '../components/footerBar';
import Info from '../challengeTyerraFrontend/BASICOS/array-propiedades.json';
import HandlerPage from '../components/pageIndex';

export default function Favoritos () {
  // const index = './'
  return (
    <div className="h-screen font-poppins">
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap" rel="stylesheet"></link>
      </Head>
      
      {/* header */}
      <header className="shadow-md">
        <NavBar />
      </header>

      <main className="my-4">

        {/* <Link href={HandlerPage()}> caja con casas */}
        <div className="shadow-md h-80 flex items-center">
          
          <div className="h-5/6 w-box flex mx-auto">
            
            <div className="w-third h-full overflow-hidden relative">
              <img className="w-fav absolute -right-36" src="/IMG/00-tyerra-h5.jpg"/>
            </div>

            <div className="ml-2 w-seventy">
              <div className="flex flex-row-reverse">
                <svg xmlns="http://www.w3.org/2000/svg" width="23.946" height="20.886" viewBox="0 0 23.946 20.886">
                  <path id="Favoritos" d="M24.422,6.344a6.3,6.3,0,0,0-8.912,0L14.3,7.558,13.081,6.344a6.3,6.3,0,1,0-8.912,8.912L5.383,16.47,14.3,25.383l8.912-8.912,1.214-1.214a6.3,6.3,0,0,0,0-8.912Z" transform="translate(-2.323 -4.497)" fill="#9482fe"/>
                </svg>
              </div>
              <h3 className="text-lg font-semibold">Casa Jardin</h3>
              <p className="text-gray">
              {Info[3].ubicacion.direccionPropiedad.ciudad}, {Info[3].ubicacion.direccionPropiedad.estado}
              </p>
              <p className="my-5 text-lg">${Info[3].precio} USD</p>
              <div className="flex">
                <p className="flex items-center text-gray">
                  <svg className="mr-2" xmlns="http://www.w3.org/2000/svg" width="22.428" height="17.441" viewBox="0 0 22.428 17.441">
                    <path id="Icon_awesome-home" data-name="Icon awesome-home" d="M10.915,6.778,3.737,12.69v6.381a.623.623,0,0,0,.623.623l4.363-.011a.623.623,0,0,0,.62-.623V15.333a.623.623,0,0,1,.623-.623h2.492a.623.623,0,0,1,.623.623v3.724a.623.623,0,0,0,.623.625l4.361.012a.623.623,0,0,0,.623-.623V12.686L11.511,6.778A.475.475,0,0,0,10.915,6.778ZM22.254,10.8,19,8.114V2.721a.467.467,0,0,0-.467-.467h-2.18a.467.467,0,0,0-.467.467V5.548L12.4,2.68a1.869,1.869,0,0,0-2.375,0L.168,10.8a.467.467,0,0,0-.062.658L1.1,12.661a.467.467,0,0,0,.658.063l9.158-7.543a.475.475,0,0,1,.6,0l9.158,7.543a.467.467,0,0,0,.658-.062l.993-1.207a.467.467,0,0,0-.066-.659Z" transform="translate(0.001 -2.254)" fill="#7e7e8b"/>
                  </svg>
                  {Info[3].m2Terreno}m2 
                </p>
                <p className="flex items-center text-gray mx-3">
                  <svg className="mr-2" xmlns="http://www.w3.org/2000/svg" width="27.39" height="16.434" viewBox="0 0 27.39 16.434">
                    <path id="Icon_awesome-bed" data-name="Icon awesome-bed" d="M7.532,12.717A3.424,3.424,0,1,0,4.109,9.293,3.428,3.428,0,0,0,7.532,12.717ZM22.6,7.239H13.01a.685.685,0,0,0-.685.685v6.163H2.739v-8.9A.685.685,0,0,0,2.054,4.5H.685A.685.685,0,0,0,0,5.185V20.25a.685.685,0,0,0,.685.685h1.37a.685.685,0,0,0,.685-.685V18.2H24.651V20.25a.685.685,0,0,0,.685.685h1.37a.685.685,0,0,0,.685-.685V12.032A4.793,4.793,0,0,0,22.6,7.239Z" transform="translate(0 -4.5)" fill="#7e7e8b"/>
                  </svg>
                  4 
                  </p>
                <p className="flex items-center text-gray">
                  <svg className="mr-2" xmlns="http://www.w3.org/2000/svg" width="20.633" height="18.054" viewBox="0 0 20.633 18.054">
                    <path id="Icon_awesome-shower" data-name="Icon awesome-shower" d="M15.7,6.425l-6.37,6.37a.967.967,0,0,1-1.368,0l-.456-.456a.967.967,0,0,1,0-1.368l0,0a4.522,4.522,0,0,1-.137-5.657,3.132,3.132,0,0,0-4.8,2.654V20.3H0V7.963a5.71,5.71,0,0,1,9.576-4.2,4.523,4.523,0,0,1,4.3.847l0,0a.967.967,0,0,1,1.368,0l.456.456A.967.967,0,0,1,15.7,6.425Zm-.228,2.918A.645.645,0,1,1,14.83,8.7.645.645,0,0,1,15.474,9.342Zm1.29,0a.645.645,0,1,1,.645.645A.645.645,0,0,1,16.764,9.342Zm3.869,0a.645.645,0,1,1-.645-.645A.645.645,0,0,1,20.633,9.342Zm-6.448,1.29a.645.645,0,1,1-.645-.645A.645.645,0,0,1,14.185,10.632Zm1.934-.645a.645.645,0,1,1-.645.645A.645.645,0,0,1,16.119,9.987Zm3.224.645a.645.645,0,1,1-.645-.645A.645.645,0,0,1,19.343,10.632ZM12.9,11.922a.645.645,0,1,1-.645-.645A.645.645,0,0,1,12.9,11.922Zm1.29,0a.645.645,0,1,1,.645.645A.645.645,0,0,1,14.185,11.922Zm3.869,0a.645.645,0,1,1-.645-.645A.645.645,0,0,1,18.054,11.922ZM12.9,13.211a.645.645,0,1,1,.645.645A.645.645,0,0,1,12.9,13.211Zm3.869,0a.645.645,0,1,1-.645-.645A.645.645,0,0,1,16.764,13.211ZM12.9,14.5a.645.645,0,1,1-.645-.645A.645.645,0,0,1,12.9,14.5Zm2.579,0a.645.645,0,1,1-.645-.645A.645.645,0,0,1,15.474,14.5Zm-1.29,1.29a.645.645,0,1,1-.645-.645A.645.645,0,0,1,14.185,15.79ZM12.9,17.08a.645.645,0,1,1-.645-.645A.645.645,0,0,1,12.9,17.08Z" transform="translate(0 -2.25)" fill="#7e7e8b"/>
                  </svg>
                  {Info[3].bathroom.completos.cantidadCompletos}
                </p>
              </div>
              <p className="uppercase my-4 text-purple">
                  Más información
                </p>

                <p className="uppercase text-purple">
                  Me interesa
                </p>
            </div>

          </div>

        </div>
        {/* </Link> */}

        {/* <Link href={HandlerPage()}> caja con casas */}
        <div className="shadow-md h-80 flex items-center">
          
          <div className="h-5/6 w-box flex mx-auto">
            
            <div className="w-third h-full overflow-hidden relative">
              <img className="w-fav absolute -right-36" src="/IMG/00-tyerra-h4.jpg"/>
            </div>

            <div className="ml-2 w-seventy">
              <div className="flex flex-row-reverse">
                <svg xmlns="http://www.w3.org/2000/svg" width="23.946" height="20.886" viewBox="0 0 23.946 20.886">
                  <path id="Favoritos" d="M24.422,6.344a6.3,6.3,0,0,0-8.912,0L14.3,7.558,13.081,6.344a6.3,6.3,0,1,0-8.912,8.912L5.383,16.47,14.3,25.383l8.912-8.912,1.214-1.214a6.3,6.3,0,0,0,0-8.912Z" transform="translate(-2.323 -4.497)" fill="#9482fe"/>
                </svg>
              </div>
              <h3 className="text-lg font-semibold">Casa Jardin</h3>
              <p className="text-gray">
              {Info[2].ubicacion.direccionPropiedad.ciudad}, {Info[3].ubicacion.direccionPropiedad.estado}
              </p>
              <p className="my-5 text-lg">${Info[3].precio} USD</p>
              <div className="flex">
                <p className="flex items-center text-gray">
                  <svg className="mr-2" xmlns="http://www.w3.org/2000/svg" width="22.428" height="17.441" viewBox="0 0 22.428 17.441">
                    <path id="Icon_awesome-home" data-name="Icon awesome-home" d="M10.915,6.778,3.737,12.69v6.381a.623.623,0,0,0,.623.623l4.363-.011a.623.623,0,0,0,.62-.623V15.333a.623.623,0,0,1,.623-.623h2.492a.623.623,0,0,1,.623.623v3.724a.623.623,0,0,0,.623.625l4.361.012a.623.623,0,0,0,.623-.623V12.686L11.511,6.778A.475.475,0,0,0,10.915,6.778ZM22.254,10.8,19,8.114V2.721a.467.467,0,0,0-.467-.467h-2.18a.467.467,0,0,0-.467.467V5.548L12.4,2.68a1.869,1.869,0,0,0-2.375,0L.168,10.8a.467.467,0,0,0-.062.658L1.1,12.661a.467.467,0,0,0,.658.063l9.158-7.543a.475.475,0,0,1,.6,0l9.158,7.543a.467.467,0,0,0,.658-.062l.993-1.207a.467.467,0,0,0-.066-.659Z" transform="translate(0.001 -2.254)" fill="#7e7e8b"/>
                  </svg>
                  {Info[3].m2Terreno}m2 
                </p>
                <p className="flex items-center text-gray mx-3">
                  <svg className="mr-2" xmlns="http://www.w3.org/2000/svg" width="27.39" height="16.434" viewBox="0 0 27.39 16.434">
                    <path id="Icon_awesome-bed" data-name="Icon awesome-bed" d="M7.532,12.717A3.424,3.424,0,1,0,4.109,9.293,3.428,3.428,0,0,0,7.532,12.717ZM22.6,7.239H13.01a.685.685,0,0,0-.685.685v6.163H2.739v-8.9A.685.685,0,0,0,2.054,4.5H.685A.685.685,0,0,0,0,5.185V20.25a.685.685,0,0,0,.685.685h1.37a.685.685,0,0,0,.685-.685V18.2H24.651V20.25a.685.685,0,0,0,.685.685h1.37a.685.685,0,0,0,.685-.685V12.032A4.793,4.793,0,0,0,22.6,7.239Z" transform="translate(0 -4.5)" fill="#7e7e8b"/>
                  </svg>
                  4 
                  </p>
                <p className="flex items-center text-gray">
                  <svg className="mr-2" xmlns="http://www.w3.org/2000/svg" width="20.633" height="18.054" viewBox="0 0 20.633 18.054">
                    <path id="Icon_awesome-shower" data-name="Icon awesome-shower" d="M15.7,6.425l-6.37,6.37a.967.967,0,0,1-1.368,0l-.456-.456a.967.967,0,0,1,0-1.368l0,0a4.522,4.522,0,0,1-.137-5.657,3.132,3.132,0,0,0-4.8,2.654V20.3H0V7.963a5.71,5.71,0,0,1,9.576-4.2,4.523,4.523,0,0,1,4.3.847l0,0a.967.967,0,0,1,1.368,0l.456.456A.967.967,0,0,1,15.7,6.425Zm-.228,2.918A.645.645,0,1,1,14.83,8.7.645.645,0,0,1,15.474,9.342Zm1.29,0a.645.645,0,1,1,.645.645A.645.645,0,0,1,16.764,9.342Zm3.869,0a.645.645,0,1,1-.645-.645A.645.645,0,0,1,20.633,9.342Zm-6.448,1.29a.645.645,0,1,1-.645-.645A.645.645,0,0,1,14.185,10.632Zm1.934-.645a.645.645,0,1,1-.645.645A.645.645,0,0,1,16.119,9.987Zm3.224.645a.645.645,0,1,1-.645-.645A.645.645,0,0,1,19.343,10.632ZM12.9,11.922a.645.645,0,1,1-.645-.645A.645.645,0,0,1,12.9,11.922Zm1.29,0a.645.645,0,1,1,.645.645A.645.645,0,0,1,14.185,11.922Zm3.869,0a.645.645,0,1,1-.645-.645A.645.645,0,0,1,18.054,11.922ZM12.9,13.211a.645.645,0,1,1,.645.645A.645.645,0,0,1,12.9,13.211Zm3.869,0a.645.645,0,1,1-.645-.645A.645.645,0,0,1,16.764,13.211ZM12.9,14.5a.645.645,0,1,1-.645-.645A.645.645,0,0,1,12.9,14.5Zm2.579,0a.645.645,0,1,1-.645-.645A.645.645,0,0,1,15.474,14.5Zm-1.29,1.29a.645.645,0,1,1-.645-.645A.645.645,0,0,1,14.185,15.79ZM12.9,17.08a.645.645,0,1,1-.645-.645A.645.645,0,0,1,12.9,17.08Z" transform="translate(0 -2.25)" fill="#7e7e8b"/>
                  </svg>
                  {Info[3].bathroom.completos.cantidadCompletos}
                </p>
              </div>
              <p className="uppercase my-4 text-purple">
                  Más información
                </p>

                <p className="uppercase text-purple">
                  Me interesa
                </p>
            </div>

          </div>

        </div>
        {/* </Link> */}

      </main>

      <FooterBar />

    </div>
  )
  
}